[2020-07-20 22:50:55,854] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: spotifyDag.get_songs 2019-10-09T01:10:00+00:00 [queued]>
[2020-07-20 22:50:55,866] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: spotifyDag.get_songs 2019-10-09T01:10:00+00:00 [queued]>
[2020-07-20 22:50:55,866] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-20 22:50:55,866] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-07-20 22:50:55,866] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-20 22:50:55,876] {taskinstance.py:900} INFO - Executing <Task(BashOperator): get_songs> on 2019-10-09T01:10:00+00:00
[2020-07-20 22:50:55,879] {standard_task_runner.py:53} INFO - Started process 18254 to run task
[2020-07-20 22:50:55,965] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: spotifyDag.get_songs 2019-10-09T01:10:00+00:00 [running]> Amandas-MacBook-Air-5.local
[2020-07-20 22:50:56,005] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/jf/jlp75ngj5yn256zck70578w40000gn/T
[2020-07-20 22:50:56,010] {bash_operator.py:105} INFO - Temporary script location: /var/folders/jf/jlp75ngj5yn256zck70578w40000gn/T/airflowtmp8qt4b6m1/get_songsrghe81mm
[2020-07-20 22:50:56,011] {bash_operator.py:115} INFO - Running command: python3 ~/Users/AmandaTran/airflow/dags/spotify_proj/dags.py
[2020-07-20 22:50:56,021] {bash_operator.py:122} INFO - Output:
[2020-07-20 22:50:56,411] {bash_operator.py:126} INFO - /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/AmandaTran/Users/AmandaTran/airflow/dags/spotify_proj/dags.py': [Errno 2] No such file or directory
[2020-07-20 22:50:56,414] {bash_operator.py:130} INFO - Command exited with return code 2
[2020-07-20 22:50:56,430] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-20 22:50:56,439] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=spotifyDag, task_id=get_songs, execution_date=20191009T011000, start_date=20200721T055055, end_date=20200721T055056
[2020-07-20 22:50:57,259] {logging_mixin.py:112} INFO - [2020-07-20 22:50:57,256] {email.py:131} INFO - Sent an alert email to ['amandatran10@gmail.com']
[2020-07-20 22:51:05,838] {logging_mixin.py:112} INFO - [2020-07-20 22:51:05,836] {local_task_job.py:103} INFO - Task exited with return code 1
